name: payroll-workflow
version: 1.0.0
description: Payroll workflow with HTTP trigger

staging-settings:
  user-workflow:
    workflow-name: payroll-workflow-staging
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.staging.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: payroll-workflow-production
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.production.json"
    secrets-path: ""