/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockSCLO__factory } from "./MockSCLO__factory";
export { PayrollConsumer__factory } from "./PayrollConsumer__factory";
